---
# tasks file for app
- name: Show env
  debug:
    msg: "This host is in {{ env }} environment."


- name: Database host
  debug:
    msg: "{{ db_host }}"

- include: ruby.yml
- include: puma.yml
