---
- name: Install Ruby, Bundler and Git
  hosts: all
  become: true
  tasks:
  - name: Install git
    become: true
    apt:
      name: git
      state: present
      update_cache: true

  - name: Install ruby and rubygems and required packages
    apt: "name={{ item }} state=present"
    with_items:
      - ruby-full
      - ruby-bundler
      - build-essential
